/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ChaosMode;

import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JPanel;

/**
 *
 * @author louay
 */
public class Meeting extends JPanel {

    public enum MeetingType {
        LECTURE, LECTURE_WITH_SEC, TUTORIAL, LAB
    }

    public enum Day {
        SATURDAY, SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY
    }

    private final MeetingType meetingType;
    private final ArrayList<MeetingTime> meetings;

    public Meeting(MeetingType meetingType) {
        super();
        initComponents();
        this.meetingType = meetingType;
        this.meetings = new ArrayList<>();
    }

    public void addMeeting(int day, int period) {
        MeetingTime meetingTime = new MeetingTime(this.meetingType, meetings.size() + 1);
        meetingTime.setMeetingTime(day, period);
        meetings.add(meetingTime);
        this.addMeetingTime();
    }

    public void addMeeting(int day, int period, int secLecDay, int secLecPeriod) {
        MeetingTime meetingTime = new MeetingTime(this.meetingType, meetings.size() + 1);
        meetingTime.setMeetingTime(day, period);
        meetingTime.setSecLecTime(secLecDay, secLecPeriod);
        meetings.add(meetingTime);
        this.addMeetingTime();
    }

    private void addMeetingTime() {

        GroupLayout timesPanelLayout = (GroupLayout) timesPanel.getLayout();

        ParallelGroup h = timesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);//timesPanelLayout.createSequentialGroup();
        SequentialGroup v = timesPanelLayout.createSequentialGroup();

        for (MeetingTime meeting : meetings) {
            h.addComponent(meeting, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE);
            v.addComponent(meeting, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(261, Short.MAX_VALUE);
        }
        timesPanelLayout.setHorizontalGroup(h);
        timesPanelLayout.setVerticalGroup(v);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newTimeButton = new javax.swing.JButton();
        timesPanel = new javax.swing.JPanel();

        newTimeButton.setText("Add new time");
        newTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTimeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timesPanelLayout = new javax.swing.GroupLayout(timesPanel);
        timesPanel.setLayout(timesPanelLayout);
        timesPanelLayout.setHorizontalGroup(
            timesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        timesPanelLayout.setVerticalGroup(
            timesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(newTimeButton)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(newTimeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTimeButtonActionPerformed
        MeetingTime meetingTime = new MeetingTime(this.meetingType, meetings.size() + 1);
        meetings.add(meetingTime);
        this.addMeetingTime();
    }//GEN-LAST:event_newTimeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newTimeButton;
    private javax.swing.JPanel timesPanel;
    // End of variables declaration//GEN-END:variables
}
