/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ChaosMode;

import java.util.ArrayList;
import javax.swing.GroupLayout;

/**
 *
 * @author louay
 */
public class Meeting extends javax.swing.JPanel {
    
    public enum MeetingType{
        LECTURE, LECTURE_WITH_SEC, TUTORIAL, LAB
    }
    
    private final MeetingType meetingType;
    private final ArrayList<MeetingTime> meetings;

    public Meeting(MeetingType meetingType) {
        super();
        initComponents();
        this.meetingType = meetingType;
        this.meetings = new ArrayList<>();
    }

    private void addMeetingTime(MeetingTime meetingTime){
        
        GroupLayout timesPanelLayout = (GroupLayout)timesPanel.getLayout();
        timesPanel.setLayout(timesPanelLayout);
        timesPanelLayout.setHorizontalGroup(
            timesPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(timesPanelLayout.createSequentialGroup()
                .addGap(10)
                .addComponent(meetingTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        timesPanelLayout.setVerticalGroup(
            timesPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(timesPanelLayout.createSequentialGroup()
                .addGap(meetings.size() * (75) + 5)
                .addComponent(meetingTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        
        meetingTime.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newTimeButton = new javax.swing.JButton();
        timesPanel = new javax.swing.JPanel();

        newTimeButton.setText("Add new time");
        newTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTimeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timesPanelLayout = new javax.swing.GroupLayout(timesPanel);
        timesPanel.setLayout(timesPanelLayout);
        timesPanelLayout.setHorizontalGroup(
            timesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        timesPanelLayout.setVerticalGroup(
            timesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(newTimeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(newTimeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTimeButtonActionPerformed
        boolean secLec = this.meetingType == MeetingType.LECTURE_WITH_SEC;
        String type;
        switch (this.meetingType){
            case LECTURE:
            case LECTURE_WITH_SEC:
                type = "Lecture";
                break;
                
            case TUTORIAL:
                type = "Tutorial";
                break;
                
            case LAB:
                type = "Lab";
                break;
                
            default: 
                type = "Unknown type";
                break;
        }
        MeetingTime meetingTime = new MeetingTime(secLec, type, meetings.size()+1);
        this.addMeetingTime(meetingTime);
        meetings.add(meetingTime);
    }//GEN-LAST:event_newTimeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newTimeButton;
    private javax.swing.JPanel timesPanel;
    // End of variables declaration//GEN-END:variables
}
