/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ChaosMode;

import GUI.ChaosMode.Meeting.Day;
import GUI.ChaosMode.Meeting.MeetingType;
import static GUI.ChaosMode.Meeting.MeetingType.LAB;
import static GUI.ChaosMode.Meeting.MeetingType.LECTURE;
import static GUI.ChaosMode.Meeting.MeetingType.LECTURE_WITH_SEC;
import static GUI.ChaosMode.Meeting.MeetingType.TUTORIAL;

/**
 *
 * @author louay
 */
public class MeetingTime extends javax.swing.JPanel {

    private final boolean secLec;

    /**
     * Creates new form MeetingTime
     *
     * @param meetingType
     * @param n
     */
    public MeetingTime(MeetingType meetingType, int n) {
        initComponents();
        
        this.secLec = meetingType == Meeting.MeetingType.LECTURE_WITH_SEC;
        String type;
        switch (meetingType){
            case LECTURE:
            case LECTURE_WITH_SEC:
                type = "Lecture";
                break;
                
            case TUTORIAL:
                type = "Tutorial";
                break;
                
            case LAB:
                type = "Lab";
                break;
                
            default: 
                type = "Unknown type";
                break;
        }
        this.secLecLabel.setVisible(secLec);
        this.secLecDay.setVisible(secLec);
        this.secLecPeriodLabel.setVisible(secLec);
        this.secLecPeriodSpinner.setVisible(secLec);
        this.meetingTypeLabel.setText(type + " " + n);
    }

    public void setMeetingTime(int day, int period) {
        this.meetingDay.setSelectedIndex(day);
        this.meetingPeriodSpinner.setValue(period);
    }

    public void setSecLecTime(int day, int period) {
        if (this.secLec) {
            this.secLecDay.setSelectedIndex(day);
            this.secLecPeriodSpinner.setValue(period);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meetingTypeLabel = new javax.swing.JLabel();
        meetingDay = new javax.swing.JComboBox<>();
        meetingPeriodLabel = new javax.swing.JLabel();
        meetingPeriodSpinner = new javax.swing.JSpinner();
        deleteMeetingButton = new javax.swing.JButton();
        secLecLabel = new javax.swing.JLabel();
        secLecDay = new javax.swing.JComboBox<>();
        secLecPeriodLabel = new javax.swing.JLabel();
        secLecPeriodSpinner = new javax.swing.JSpinner();

        meetingTypeLabel.setText("jLabel1");

        meetingDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday" }));

        meetingPeriodLabel.setText("Period");

        meetingPeriodSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));

        deleteMeetingButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteMeetingButton.setText("Delete Meeting");
        deleteMeetingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMeetingButtonActionPerformed(evt);
            }
        });

        secLecLabel.setText("Secondary Lecture");

        secLecDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday" }));

        secLecPeriodLabel.setText("Period");

        secLecPeriodSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meetingTypeLabel)
                    .addComponent(secLecLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meetingDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(meetingPeriodLabel)
                        .addGap(18, 18, 18)
                        .addComponent(meetingPeriodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteMeetingButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secLecDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(secLecPeriodLabel)
                        .addGap(18, 18, 18)
                        .addComponent(secLecPeriodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meetingTypeLabel)
                    .addComponent(meetingDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meetingPeriodLabel)
                    .addComponent(meetingPeriodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteMeetingButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secLecLabel)
                    .addComponent(secLecDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secLecPeriodLabel)
                    .addComponent(secLecPeriodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteMeetingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMeetingButtonActionPerformed

    }//GEN-LAST:event_deleteMeetingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteMeetingButton;
    private javax.swing.JComboBox<String> meetingDay;
    private javax.swing.JLabel meetingPeriodLabel;
    private javax.swing.JSpinner meetingPeriodSpinner;
    private javax.swing.JLabel meetingTypeLabel;
    private javax.swing.JComboBox<String> secLecDay;
    private javax.swing.JLabel secLecLabel;
    private javax.swing.JLabel secLecPeriodLabel;
    private javax.swing.JSpinner secLecPeriodSpinner;
    // End of variables declaration//GEN-END:variables
}
