/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ChaosMode;

import Core.InfoHelpers.GroupInfo;
import Core.InfoHelpers.SubjectInfo;
import GUI.ChaosMode.Meeting.MeetingType;

/**
 *
 * @author louay
 */
public class SubjectPanelChaos extends javax.swing.JPanel {

    private final SubjectInfo subjectInfo;
    private final String subjectName;
    private Meeting lectures, tutorials, labs;
    
    public String getSubjectName() {
        return subjectName;
    }
    
    /**
     * Creates new form SubjectPanel
     * @param subjectName
     * @param secLecExists
     * @param tutExists
     * @param tutBiWeek
     * @param labExists
     * @param labBiweek
     */
    public SubjectPanelChaos(String subjectName, boolean secLecExists, boolean tutExists, boolean tutBiWeek, boolean labExists, boolean labBiweek) {
        subjectInfo = new SubjectInfo(secLecExists, tutExists, tutBiWeek, labExists, labBiweek);
        this.subjectName = subjectName;
        initComponents();
        if (secLecExists){
            this.lectures = new Meeting(MeetingType.LECTURE_WITH_SEC);
        } else {
            this.lectures = new Meeting(MeetingType.LECTURE);
        }
        this.tutorials = new Meeting(MeetingType.TUTORIAL);
        this.labs = new Meeting(MeetingType.LAB);
        this.subjectTabbedPane.addTab("Lectures", lectures);
        this.subjectTabbedPane.addTab("Tutorials", tutorials);
        this.subjectTabbedPane.addTab("Labs", labs);
    }
    
    public void addGroup(GroupInfo groupInfo){
        if (this.subjectInfo.secLecExists){
            lectures.addMeeting(groupInfo.lecture.day, groupInfo.lecture.period, groupInfo.secLecture.day, groupInfo.secLecture.period);
        } else {
            lectures.addMeeting(groupInfo.lecture.day, groupInfo.lecture.period);
        }
        
        if (this.subjectInfo.tutExists){
            tutorials.addMeeting(groupInfo.tutorial1.day, groupInfo.tutorial1.period);
            if (!this.subjectInfo.tutBiWeek){
                tutorials.addMeeting(groupInfo.tutorial2.day, groupInfo.tutorial2.period);
            }
        }
        
        if (this.subjectInfo.labExists){
            labs.addMeeting(groupInfo.lab1.day, groupInfo.lab1.period);
            if (!this.subjectInfo.labBiWeek){
                labs.addMeeting(groupInfo.lab2.day, groupInfo.lab2.period);
            }
        }
    }
    
    public void reset(){
        this.subjectTabbedPane.removeTabAt(0);
        this.subjectTabbedPane.removeTabAt(0);
        this.subjectTabbedPane.removeTabAt(0);
        if (this.subjectInfo.secLecExists){
            this.lectures = new Meeting(MeetingType.LECTURE_WITH_SEC);
        } else {
            this.lectures = new Meeting(MeetingType.LECTURE);
        }
        this.tutorials = new Meeting(MeetingType.TUTORIAL);
        this.labs = new Meeting(MeetingType.LAB);
        this.subjectTabbedPane.addTab("Lectures", lectures);
        this.subjectTabbedPane.addTab("Tutorials", tutorials);
        this.subjectTabbedPane.addTab("Labs", labs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectTabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subjectTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subjectTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane subjectTabbedPane;
    // End of variables declaration//GEN-END:variables
}
