/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ChaosMode;

import Core.InfoHelpers.SubjectInfo;
import GUI.MainGUI;
import java.util.ArrayList;

/**
 *
 * @author louay
 */
public class SubjectPanelChaos extends javax.swing.JPanel {

    private final SubjectInfo subjectInfo;
    private final String subjectName;
    
    /**
     * Creates new form SubjectPanel
     * @param subjectName
     * @param secLecExists
     * @param tutExists
     * @param tutBiWeek
     * @param labExists
     * @param labBiweek
     */
    public SubjectPanelChaos(String subjectName, boolean secLecExists, boolean tutExists, boolean tutBiWeek, boolean labExists, boolean labBiweek) {
        subjectInfo = new SubjectInfo(secLecExists, tutExists, tutBiWeek, labExists, labBiweek);
        this.subjectName = subjectName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectTabbedPane = new javax.swing.JTabbedPane();
        lecPanel = new javax.swing.JPanel();
        tutPanel = new javax.swing.JPanel();
        labPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout lecPanelLayout = new javax.swing.GroupLayout(lecPanel);
        lecPanel.setLayout(lecPanelLayout);
        lecPanelLayout.setHorizontalGroup(
            lecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        lecPanelLayout.setVerticalGroup(
            lecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        subjectTabbedPane.addTab("Lectures", lecPanel);

        javax.swing.GroupLayout tutPanelLayout = new javax.swing.GroupLayout(tutPanel);
        tutPanel.setLayout(tutPanelLayout);
        tutPanelLayout.setHorizontalGroup(
            tutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        tutPanelLayout.setVerticalGroup(
            tutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        subjectTabbedPane.addTab("Tutorials", tutPanel);

        javax.swing.GroupLayout labPanelLayout = new javax.swing.GroupLayout(labPanel);
        labPanel.setLayout(labPanelLayout);
        labPanelLayout.setHorizontalGroup(
            labPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        labPanelLayout.setVerticalGroup(
            labPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        subjectTabbedPane.addTab("Labs", labPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subjectTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(subjectTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel labPanel;
    private javax.swing.JPanel lecPanel;
    private javax.swing.JTabbedPane subjectTabbedPane;
    private javax.swing.JPanel tutPanel;
    // End of variables declaration//GEN-END:variables
}
