/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.PreGenerator;

import Core.Differentiator;
import Core.Generator;
import GUI.PostGenerator.ResultMainGui;
import GUI.PreGenerator.Files.FileLoader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author louay
 */
public class MainGUI extends javax.swing.JFrame {

    private final ArrayList<SubjectPanel> subjects;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        labBiWeekCheckBox.setVisible(false);
        tutBiWeekCheckBox.setVisible(false);
        subjects = new ArrayList<>();
    }

    private void startScheduleGeneration(String str) {
        ArrayList<String[][]> results = Generator.getGeneratedSchedules(str);
        try {
            Differentiator.differentiate(this, results);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            generateButton.setText("Generate");
            new ResultMainGui(results);
        }
    }

    private void saveToFile(String str) {
        String path = MainGUI.class.getProtectionDomain().getCodeSource().getLocation().getPath();
        path = (new File(path)).getParentFile().getPath();
        String fileName = JOptionPane.showInputDialog(null, "Enter file name", "Save file", JOptionPane.INFORMATION_MESSAGE) + ".SGEN";
        path += (File.separator + fileName);
        try {
            PrintWriter writer = new PrintWriter(path, "UTF-8");
            writer.println(str);
            writer.close();
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String generateInputString() {
        StringBuilder sb = new StringBuilder();
        sb.append(this.subjectsTabbedPane.getTabCount()).append("\r\n\r\n");
        try {
            for (SubjectPanel s : subjects) {
                sb.append(s.generateSubjectString()).append("\r\n");
            }
            return sb.toString();
        } catch (Exception ex) {
            String error = ex.getMessage();
            JOptionPane.showMessageDialog(null, error, "Cannot generate", JOptionPane.ERROR_MESSAGE);
            return "Error";
        }
    }

    public SubjectPanel addSubject(String subjectName, boolean secLecExists, boolean tutExists, boolean tutBiWeek, boolean labExists, boolean labBiweek) {
        SubjectPanel subject = new SubjectPanel(subjectName, secLecExists, tutExists, tutBiWeek, labExists, labBiweek);
        subjects.add(subject);
        subjectsTabbedPane.addTab(subjectName, subject);
        subjectNameTextField.setText("");
        return subject;
    }
    
    public String getMeetingType(String subjectName, int day, int period) throws Exception{
        for (SubjectPanel subject : subjects){
            if (subjectName.equals(subject.getSubjectName())){
                try {
                    return subject.getMeetingType(day, period);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
            }
        }
        throw new Exception("Internal fatal error");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSubjectButton = new javax.swing.JButton();
        subjectsTabbedPane = new javax.swing.JTabbedPane();
        subjectNameTextField = new javax.swing.JTextField();
        secondaryLectureCheckBox = new javax.swing.JCheckBox();
        tutorialCheckBox = new javax.swing.JCheckBox();
        tutBiWeekCheckBox = new javax.swing.JCheckBox();
        labCheckBox = new javax.swing.JCheckBox();
        labBiWeekCheckBox = new javax.swing.JCheckBox();
        generateButton = new javax.swing.JButton();
        loadFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addSubjectButton.setText("Add Subject");
        addSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectButtonActionPerformed(evt);
            }
        });

        secondaryLectureCheckBox.setText("Secondary bi-weekly lecture");

        tutorialCheckBox.setText("Tutorial");
        tutorialCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialCheckBoxActionPerformed(evt);
            }
        });

        tutBiWeekCheckBox.setText("Bi-weekly?");

        labCheckBox.setText("Lab");
        labCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labCheckBoxActionPerformed(evt);
            }
        });

        labBiWeekCheckBox.setText("Bi-weekly?");

        generateButton.setBackground(new java.awt.Color(51, 153, 0));
        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        loadFileButton.setText("Load File");
        loadFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileButtonActionPerformed(evt);
            }
        });

        saveFileButton.setText("Save to file");
        saveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectsTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labCheckBox)
                                            .addComponent(tutorialCheckBox))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tutBiWeekCheckBox)
                                            .addComponent(labBiWeekCheckBox)))
                                    .addComponent(secondaryLectureCheckBox)))
                            .addComponent(subjectNameTextField))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(addSubjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(saveFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(loadFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondaryLectureCheckBox))
                            .addComponent(addSubjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tutorialCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tutBiWeekCheckBox, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labCheckBox)
                                    .addComponent(labBiWeekCheckBox))
                                .addGap(13, 13, 13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loadFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(subjectsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectButtonActionPerformed
        if (subjectNameTextField.getText() == null || subjectNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Subject name can not be empty!", "Subject name error", JOptionPane.ERROR_MESSAGE);
        } else {
            SubjectPanel subject = new SubjectPanel(
                    subjectNameTextField.getText(),
                    secondaryLectureCheckBox.isSelected(),
                    tutorialCheckBox.isSelected(),
                    tutBiWeekCheckBox.isSelected(),
                    labCheckBox.isSelected(),
                    labBiWeekCheckBox.isSelected());
            subjects.add(subject);
            subjectsTabbedPane.addTab(subjectNameTextField.getText(), subject);
            subjectNameTextField.setText("");
        }
    }//GEN-LAST:event_addSubjectButtonActionPerformed

    private void tutorialCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialCheckBoxActionPerformed
        tutBiWeekCheckBox.setVisible(tutorialCheckBox.isSelected());
    }//GEN-LAST:event_tutorialCheckBoxActionPerformed

    private void labCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labCheckBoxActionPerformed
        labBiWeekCheckBox.setVisible(labCheckBox.isSelected());
    }//GEN-LAST:event_labCheckBoxActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        this.startScheduleGeneration(generateInputString());
    }//GEN-LAST:event_generateButtonActionPerformed

    private void loadFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(null);
        String path;
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            path = file.getAbsolutePath();
            System.out.println("\nYou chose to open this file: " + file.getName());
            System.out.println("In this location: " + path);
            FileLoader fileLoader = new FileLoader(file);
            fileLoader.loadFile(this);
        }
    }//GEN-LAST:event_loadFileButtonActionPerformed

    private void saveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileButtonActionPerformed
        this.saveToFile(generateInputString());
    }//GEN-LAST:event_saveFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JCheckBox labBiWeekCheckBox;
    private javax.swing.JCheckBox labCheckBox;
    private javax.swing.JButton loadFileButton;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JCheckBox secondaryLectureCheckBox;
    private javax.swing.JTextField subjectNameTextField;
    private javax.swing.JTabbedPane subjectsTabbedPane;
    private javax.swing.JCheckBox tutBiWeekCheckBox;
    private javax.swing.JCheckBox tutorialCheckBox;
    // End of variables declaration//GEN-END:variables
}
