/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.PreGenerator;

import GUI.Extras.GroupInfo;
import GUI.Extras.SubjectInfo;
import GUI.PreGenerator.GroupPanel.SecondLecturePossibility;
import java.util.ArrayList;

/**
 *
 * @author louay
 */
public class SubjectPanel extends javax.swing.JPanel {

    private final SubjectInfo subjectInfo;
    private final ArrayList<GroupPanel> groups;
    private final String subjectName;

    /**
     * Creates new form SubjectPanel
     *
     * @param secLecExists
     * @param tutExists
     * @param tutBiWeek
     * @param labExists
     * @param labBiweek
     */
    public SubjectPanel(String subjectName, boolean secLecExists, boolean tutExists, boolean tutBiWeek, boolean labExists, boolean labBiweek) {
        subjectInfo = new SubjectInfo(secLecExists, tutExists, tutBiWeek, labExists, labBiweek);
        groups = new ArrayList<>();
        this.subjectName = subjectName;
        initComponents();
    }

    public void setGroups(ArrayList<GroupInfo> groupsInfo) {
        for (GroupInfo groupInfo : groupsInfo) {
            GroupPanel newGroup = new GroupPanel(subjectInfo);
            groups.add(newGroup);
            groupsTabbedPane.addTab("Group " + (groupsTabbedPane.getTabCount() + 1), newGroup);
            newGroup.setGroupInfo(groupInfo);
        }
    }

    public String generateSubjectString() throws Exception {
        StringBuilder sb = new StringBuilder();
        sb.append(this.subjectName).append("\r\n");
        sb.append(this.groupsTabbedPane.getTabCount()).append(" ");

        SecondLecturePossibility p = SecondLecturePossibility.NO_SEC_LEC;
        if (this.subjectInfo.secLecExists) {
            for (GroupPanel g : this.groups) {
                SecondLecturePossibility current = g.checkSecLecturePossibility();
                if (current.ordinal() == 0) {
                    break;
                } else if (current.ordinal() > p.ordinal()) {
                    p = current;
                }
            }
            if (p.equals(SecondLecturePossibility.NOT_POSSIBLE)) {
                throw new Exception("-1");
            } else {
                for (GroupPanel g : this.groups) {
                    g.setSecondLecturePlace(p);
                }
            }
        }

        switch (p) {
            case NO_SEC_LEC:
            case MAIN_LECTURE: {
                if (!this.subjectInfo.tutExists) {
                    sb.append("0 ");
                } else {
                    sb.append("2 ");
                }

                if (!this.subjectInfo.labExists) {
                    sb.append("0\r\n\r\n");
                } else {
                    sb.append("2\r\n\r\n");
                }
                break;
            }

            case TUTORIAL: {
                sb.append("1 ");
                if (!this.subjectInfo.labExists) {
                    sb.append("0\r\n\r\n");
                } else {
                    sb.append("2\r\n\r\n");
                }
                break;
            }

            case LAB: {
                if (!this.subjectInfo.tutExists) {
                    sb.append("0 ");
                } else {
                    sb.append("2 ");
                }
                sb.append("1\r\n\r\n");
                break;
            }
        }

        for (GroupPanel g : this.groups) {
            sb.append(g.generateString()).append("\r\n");
        }

        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupsTabbedPane = new javax.swing.JTabbedPane();
        newGroupButton = new javax.swing.JButton();

        newGroupButton.setText("New group");
        newGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGroupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupsTabbedPane)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(newGroupButton)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newGroupButton)
                .addGap(10, 10, 10)
                .addComponent(groupsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGroupButtonActionPerformed
        GroupPanel newGroup = new GroupPanel(subjectInfo);
        groups.add(newGroup);
        groupsTabbedPane.addTab("Group " + (groupsTabbedPane.getTabCount() + 1), newGroup);
    }//GEN-LAST:event_newGroupButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane groupsTabbedPane;
    private javax.swing.JButton newGroupButton;
    // End of variables declaration//GEN-END:variables
}
